###############################################################
# Makefile for Fran (!GHC!)
################################################################

all	: sokoban.exe

HS	= SokoBoard.hs SokoDemo.hs SokoDraw.hs SokoType.hs \
	  Sokoban.hs SokoMain.hs

FRAN = ../..
include $(FRAN)/app.mk

sokoban.exe	: $(OBJS)


include _depend
